roomShapes:
- name: "small_rect"
  template:
    name: "rectangle"
    params:
      size-x: "5-10"
      size-y: "4-8"
  shape: null
- name: "small_sq"
  template:
    name: "square"
    params:
      size: "5-10"
  shape: null
- name: "heart"
  template: null
  shape:
  - "..x...x.."
  - ".xxx.xxx."
  - "xxxxxxxxx"
  - ".xxxxxxx."
  - "..xxxxx.."
  - "...xxx..."
  - "....x...."
- name: "diamond"
  template: null
  shape:
  - ".....x....."
  - "....xxx...."
  - "...xxxxx..."
  - "..xxxxxxx.."
  - ".xxxxxxxxx."
  - "xxxxxxxxxxx"
  - ".xxxxxxxxx."
  - "..xxxxxxx.."
  - "...xxxxx..."
  - "....xxx...."
  - ".....x....."
- name: "big_square"
  template:
    name: "square"
    params:
      size: "20-25"
  shape: null
- name: "mega room"
  template:
    name: "rectangle"
    params:
      size-x: "50-75"
      size-y: "50-75"
  shape: null
rooms:
- name: "basic"
  shape: "small_rect"
  amount: "500-1000"
  rotate: "false"
- name: "basic2"
  shape: "small_sq"
  amount: "500-1000"
  rotate: "false"
- name: "heart"
  shape: "heart"
  amount: "200-400"
  rotate: "true"
- name: "diamond"
  shape: "diamond"
  amount: "100-200"
  rotate: "true"
- name: "boss"
  shape: "big_square"
  amount: "10-50"
  rotate: "false"
- name: "mega"
  shape: "mega room"
  amount: "1-10"
  rotate: "false"
outputFileType: "YAML"
seed: null
